<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderManagementSubsystem.Aggregators\OrderManagementSubsystem.Aggregators.csproj" />
    <ProjectReference Include="..\OrderManagementSubsystem.DTOs\OrderManagementSubsystem.DTOs.csproj" />
    <ProjectReference Include="..\OrderManagementSubsystem.Repository\OrderManagementSubsystem.Repository.csproj" />
    <ProjectReference Include="..\SharedSubSystem\SharedSubSystem.csproj" />
  </ItemGroup>

</Project>
